## Google Music Media Player
## Supplemental 'package.yaml' file for "gmusic_player"
input_select:
  gmusic_player_source:
    name: Source
    icon: mdi:library-music
    options:
    - "Playlist"
    - "Station"

  gmusic_player_playlist:
    name: Playlist
    icon: mdi:playlist-music
    options: ## Should be empty
    - " "

  gmusic_player_station:
    name: Station
    icon: mdi:playlist-music
    options:  ## Should be empty
    - " "

## Sensor used for auto track advance.
sensor:
  - platform: template
    sensors:
      gmusic_receiver:
        value_template: "{{ states.media_player.gmusic_player.attributes._player_state }}"

automation old:
  - alias: "gmusic_player_auto_advance"
    initial_state: 'on'
    trigger:
      platform: state
      #value_template: "{{ states.media_player.gmusic_player.attributes._player_state }}"
      entity_id: 'sensor.gmusic_receiver'
      from: 'playing'
      to: 'idle'
      for:
        seconds: 1
    condition:
      - condition: state
        entity_id: 'media_player.gmusic_player'
        state: 'playing'
    action:
      - service: media_player.media_next_track
        entity_id: 'media_player.gmusic_player'

  - alias: "gmusic_player_auto_play"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: 'media_player.gmusic_player'
      from: 'off'
      to: 'idle'
    action:
      - service: media_player.media_play
        entity_id: 'media_player.gmusic_player'


## ------------------------------------------------------------------------- ,
##  --------------   The rest of this file is optional    ----------------
## ------------------------------------------------------------------------- ,
homeassistant:
  customize:
    media_player.gmusic_player:
      friendly_name: "Google Music Player"

    sensor.gmusic_receiver:
      friendly_name: "Google Music Receiver"
      hidden: true

## This group may only be visable when using the "states UI"
group:
  google_music_media_player:
    name: Google Music
    entities:
    - media_player.gmusic_player
    - input_select.gmusic_player_speakers
    - input_select.gmusic_player_source
    - input_select.gmusic_player_playlist
    - input_select.gmusic_player_station
